INHERIT: ../base.yml
site_name: Digitalizaci贸n - Glosario
site_dir: ../../docs/glosario

nav:
  - Inicio: index.md
  - UD1:
    - ud1.md
    - Digitalizaci贸n y Transformaci贸n Digital: digitalizacion.md
    - IT y OT: it-ot.md
    - Departamentos IT y roles: departamentos-it.md
    - Inteligencia Artificial: ia.md
    - Machine Learning y Deep Learning: ml-dl.md
    - Inteligencia Artificial Generativa: iag.md
    - Grandes Modelos de Lenguaje: llm.md
    - Retrieval Augmented Generation: rag.md
    - Agentes: agentes.md
    - Sistemas complejos: sistemas-complejos.md
  - UD2:
    - ud2.md
    - Big Data: big-data.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iesalberticadiz
      name: IES Rafael Alberti en Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/IES-Rafael-Alberti/digitalizacion-gs
      name: Repositorio del m贸dulo

plugins:
  - search:
      lang: es

copyright: Contenido generado por el equipo educativo del IES Rafael Alberti