INHERIT: ../base.yml
site_name: Digitalización - Glosario
site_dir: ../../docs/glosario

nav:
  - Inicio: index.md
  - UD1:
    - ud1.md
    - Digitalización y Transformación Digital: digitalizacion.md
    - IT y OT: it-ot.md
    - Departamentos IT y roles: departamentos-it.md
    - Inteligencia Artificial: ia.md
    - Machine Learning y Deep Learning: ml-dl.md
    - Inteligencia Artificial Generativa: iag.md
    - Grandes Modelos de Lenguaje: llm.md
    - Retrieval Augmented Generation: rag.md
    - Agentes: agentes.md
    - Sistemas complejos: sistemas-complejos.md
  - UD2:
    - ud2.md
    - Big Data: bigdata.md
    - Ciberseguridad y privacidad de la información: ciberseguridad.md
    - Principales amenazas y copias de seguridad: amenazas.md
    - Autenticación y contraseñas: autenticacion.md
    - Tecnologías Habilitadoras Digitales. 5G, Impresión 3D y Robótica Colaborativa: thd.md
    - Blockchain y activos digitales: blockchain.md
    - Realidad Virtual y Realidad Aumentada: rarv.md
    - Internet de las Cosas y Gemelos Digitales: iot.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iesalberticadiz
      name: IES Rafael Alberti en Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/IES-Rafael-Alberti/digitalizacion-gs
      name: Repositorio del módulo

plugins:
  - search:
      lang: es

copyright: Contenido generado por el equipo educativo del IES Rafael Alberti